name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java (required by Gradle / Android build)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Cache Gradle dependencies for faster builds
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Make gradlew executable (important on Linux runners)
      - name: Make Gradlew executable
        run: chmod +x gradlew

      # Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Upload Debug APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MoneroAlert-Debug
          path: app/build/outputs/apk/debug/app-debug.apk

  # (Optional) Run tests
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make Gradlew executable
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew test
